apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-cloudevents-controller
  namespace: tekton-cloudevents
  labels:
    app.kubernetes.io/component: tekton-cloudevents-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-cloudevents
