apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-cloudevents-controller
  namespace: tekton-cloudevents
  labels:
    app.kubernetes.io/component: tekton-cloudevents-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-cloudevents
subjects:
  - kind: ServiceAccount
    name: tekton-cloudevents-controller
    namespace: tekton-cloudevents
roleRef:
  kind: Role
  name: tekton-cloudevents-controller
  apiGroup: rbac.authorization.k8s.io
