apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tekton-cloudevents-controller
    app.kubernetes.io/component: tekton-cloudevents-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: tekton-cloudevents
    # tekton.dev/release value replaced with inputs.params.versionTag in pipeline/tekton/publish.yaml
    pipeline.tekton.dev/release: "devel"
    # labels below are related to istio and should not be used for resource lookup
    app: tekton-cloudevents-controller
    version: "devel"
  name: tekton-cloudevents-controller
  namespace: tekton-cloudevents
spec:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: tekton-cloudevents-controller
    app.kubernetes.io/component: tekton-cloudevents-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-cloudevents
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-cloudevents-controller
  namespace: tekton-cloudevents
  labels:
    app.kubernetes.io/name: tekton-cloudevents-controller
    app.kubernetes.io/component: tekton-cloudevents-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: tekton-cloudevents
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-cloudevents-controller
      app.kubernetes.io/component: tekton-cloudevents-controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-cloudevents
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: tekton-cloudevents-controller
        app.kubernetes.io/component: tekton-cloudevents-controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: devel
        app.kubernetes.io/part-of: tekton-cloudevents
        app: tekton-cloudevents-controller
    spec:
      serviceAccountName: tekton-cloudevents-controller
      containers:
      - name: tekton-cloudevents-controller
        image: ko://github.com/tektoncd/experimental/cloudevents/cmd/controller
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # If you are changing these names, you will also need to update
        # the controller's Role in 200-role.yaml to include the new
        # values in the "configmaps" "get" rule.
        - name: CONFIG_LOGGING_NAME
          value: config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
