apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  # Knative's serverless capabilities will work anywhere in namespaces listed below
  # It is important that the Tekton Pipelines installation namespace is not mentioned here
  # or the user will encounter admission webhook timeout problems on OpenShift 4.2
  - knative-serving
  - kabanero