# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
data: null
kind: ConfigMap
metadata:
  name: {{ template "pipeline.fullname" . }}-artifact-bucket
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
data:
{{ .Values.controller.config.artifactBucket | toYaml | indent 2 }}
---
apiVersion: v1
data: null
kind: ConfigMap
metadata:
  name: {{ template "pipeline.fullname" . }}-artifact-pvc
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
data:
{{ .Values.controller.config.artifactPvc | toYaml | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  # name: {{ template "pipeline.fullname" . }}-defaults
  name: config-defaults
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
data:
{{ .Values.controller.config.defaults | toYaml | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pipeline.fullname" . }}-feature-flags
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
data:
{{ .Values.controller.config.featureFlags | toYaml | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pipeline.fullname" . }}-leader-election
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
data:
{{ .Values.controller.config.leaderElection | toYaml | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pipeline.fullname" . }}-logging
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
data:
{{ .Values.controller.config.logging | toYaml | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pipeline.fullname" . }}-observability
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
data:
{{ .Values.controller.config.observability | toYaml | indent 2 }}
