# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.controller.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pipeline.fullname" . }}-controller
  labels:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.helmLabels" . | nindent 4 }}
    {{- include "pipeline.versionLabels" . | nindent 4 }}
    {{- include "pipeline.componentLabels" "controller" | nindent 4 }}
    {{- include "pipeline.nameLabels" "controller" | nindent 4 }}
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - name: {{ .Values.controller.metrics.portName }}
      port: {{ .Values.controller.metrics.port }}
      protocol: TCP
      targetPort: 9090
  selector:
    {{- include "pipeline.baseLabels" . | nindent 4 }}
    {{- include "pipeline.componentLabels" "controller" | nindent 4 }}
    {{- include "pipeline.nameLabels" "controller" | nindent 4 }}
{{- end }}
