# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tekton
from tekton.models.v1beta1_condition_check_status import V1beta1ConditionCheckStatus  # noqa: E501
from tekton.rest import ApiException


class TestV1beta1ConditionCheckStatus(unittest.TestCase):
    """V1beta1ConditionCheckStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1ConditionCheckStatus(self):
        """Test V1beta1ConditionCheckStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tekton.models.v1beta1_condition_check_status.V1beta1ConditionCheckStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
