FROM golang:1.12-alpine

RUN apk add curl git

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/tektoncd/experimental/webhooks-extension
WORKDIR /go/src/github.com/tektoncd/experimental/webhooks-extension

# Install dep and verify dependencies
ADD https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep
RUN dep ensure -vendor-only

# Run endpoints go tests
RUN CGO_ENABLED=0 go test github.com/tektoncd/experimental/webhooks-extension/pkg/endpoints -v
