# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/tektoncd/experimental/webhooks-extension
WORKDIR /go/src/github.com/tektoncd/experimental/webhooks-extension

# Install dep and verify dependencies
ADD https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep
RUN dep ensure -vendor-only

# Run endpoints go tests
RUN go test github.com/tektoncd/experimental/webhooks-extension/endpoints -v
