apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: scheduler-framework-sample
    leaderElection:
      leaderElect: true
      lockObjectName: scheduler-framework-sample
      lockObjectNamespace: kube-system
    plugins:
      queueSort:
        enabled:
        - name: CoschedulerSamenode
        disabled:
        - name: "*"
      preFilter:
        enabled:
        - name: CoschedulerSamenode
      filter:
        enabled:
        - name: CoschedulerSamenode
      postBind:
        enabled:
        - name: CoschedulerSamenode