apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: echo-good-morning-run
spec:
  spec:
    apiVersion: tekton.dev/v1alpha1
    kind: ColocatedPipelineRun
    # metadata: # for labels and annotations
    spec:
      timeouts:
        pipeline: 5m
      params:
      - name: git-url
        value: "https://github.com/tektoncd/pipeline"
      workspaces:
      - name: source-code
        emptyDir: {}
      pipelineSpec:
        params:
        - name: git-url
          type: string
        tasks:
        - name: clone
          params:
          - name: url
            value: $(params.git-url)
          taskSpec:
            workspaces:
            - name: output
            steps:
              - name: git-clone
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo "$(params.url)" >> $(workspaces.output.path)
          workspaces:
          - name: output
            workspace: source-code
        - name: echo-good-afternoon
          taskSpec:
            steps:
              - name: echo2
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo "Good Afternoon!"
          runAfter:
          - clone
        - name: echo-good-morning
          taskSpec:
            steps:
              - name: echo2
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo "Good Morning!"
          runAfter:
          - clone
         
