apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: echo-good-morning-run
spec:
  spec:
    apiVersion: tekton.dev/v1alpha1
    kind: ColocatedPipelineRun
    # metadata: # for labels and annotations
    spec:
      timeouts:
        pipeline: 15s
      params:
      - name: greeting
        value: "Good Morning!"
      pipelineSpec:
        params:
        - name: greeting
          type: string
        tasks:
        - name: echo-good-morning
          params:
          - name: greeting
            value: $(params.greeting)
          taskSpec:
            steps:
              - name: echo
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo "$(params.greeting)"
                  sleep 20
        - name: echo-good-afternoon
          taskSpec:
            steps:
              - name: echo2
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo "Good Afternoon!"
          runAfter:
          - echo-good-morning
