apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: echo-good-morning-with-taskrefs
spec:
  spec:
    apiVersion: tekton.dev/v1alpha1
    kind: ColocatedPipelineRun
    # metadata: # for labels and annotations
    spec:
      timeouts:
        pipeline: 5m
      pipelineSpec:
        tasks:
        - name: echo-good-morning
          params:
          - name: greeting
            value: "Good Morning!"
          taskRef:
            name: echo-greeting
        - name: echo-good-afternoon
          params:
          - name: greeting
            value: "Good Afternoon!"
          taskRef:
            name: echo-greeting
          runAfter:
          - echo-good-morning
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-greeting
spec:
  params:
  - name: greeting
    type: string 
  steps:
  - name: echo
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo "$(params.greeting)"
