apiVersion: v1
kind: Service
metadata:
  name: tekton-webhooks-extension-validator
  namespace: tekton-pipelines
spec:
  type: ClusterIP
  selector:
    app: tekton-webhooks-extension-validator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080