/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/tektoncd/experimental/metrics-operator/pkg/apis/monitoring/v1alpha1"
	scheme "github.com/tektoncd/experimental/metrics-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PipelineRunMonitorsGetter has a method to return a PipelineRunMonitorInterface.
// A group's client should implement this interface.
type PipelineRunMonitorsGetter interface {
	PipelineRunMonitors(namespace string) PipelineRunMonitorInterface
}

// PipelineRunMonitorInterface has methods to work with PipelineRunMonitor resources.
type PipelineRunMonitorInterface interface {
	Create(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.CreateOptions) (*v1alpha1.PipelineRunMonitor, error)
	Update(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.UpdateOptions) (*v1alpha1.PipelineRunMonitor, error)
	UpdateStatus(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.UpdateOptions) (*v1alpha1.PipelineRunMonitor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PipelineRunMonitor, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PipelineRunMonitorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelineRunMonitor, err error)
	PipelineRunMonitorExpansion
}

// pipelineRunMonitors implements PipelineRunMonitorInterface
type pipelineRunMonitors struct {
	client rest.Interface
	ns     string
}

// newPipelineRunMonitors returns a PipelineRunMonitors
func newPipelineRunMonitors(c *MetricsV1alpha1Client, namespace string) *pipelineRunMonitors {
	return &pipelineRunMonitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pipelineRunMonitor, and returns the corresponding pipelineRunMonitor object, and an error if there is any.
func (c *pipelineRunMonitors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PipelineRunMonitor, err error) {
	result = &v1alpha1.PipelineRunMonitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PipelineRunMonitors that match those selectors.
func (c *pipelineRunMonitors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PipelineRunMonitorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PipelineRunMonitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pipelineRunMonitors.
func (c *pipelineRunMonitors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pipelineRunMonitor and creates it.  Returns the server's representation of the pipelineRunMonitor, and an error, if there is any.
func (c *pipelineRunMonitors) Create(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.CreateOptions) (result *v1alpha1.PipelineRunMonitor, err error) {
	result = &v1alpha1.PipelineRunMonitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineRunMonitor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pipelineRunMonitor and updates it. Returns the server's representation of the pipelineRunMonitor, and an error, if there is any.
func (c *pipelineRunMonitors) Update(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.UpdateOptions) (result *v1alpha1.PipelineRunMonitor, err error) {
	result = &v1alpha1.PipelineRunMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		Name(pipelineRunMonitor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineRunMonitor).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pipelineRunMonitors) UpdateStatus(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.UpdateOptions) (result *v1alpha1.PipelineRunMonitor, err error) {
	result = &v1alpha1.PipelineRunMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		Name(pipelineRunMonitor.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineRunMonitor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pipelineRunMonitor and deletes it. Returns an error if one occurs.
func (c *pipelineRunMonitors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pipelineRunMonitors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pipelineRunMonitor.
func (c *pipelineRunMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelineRunMonitor, err error) {
	result = &v1alpha1.PipelineRunMonitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pipelinerunmonitors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
