/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/tektoncd/experimental/task-loops/pkg/apis/taskloop/v1alpha1"
	scheme "github.com/tektoncd/experimental/task-loops/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TaskLoopsGetter has a method to return a TaskLoopInterface.
// A group's client should implement this interface.
type TaskLoopsGetter interface {
	TaskLoops(namespace string) TaskLoopInterface
}

// TaskLoopInterface has methods to work with TaskLoop resources.
type TaskLoopInterface interface {
	Create(ctx context.Context, taskLoop *v1alpha1.TaskLoop, opts v1.CreateOptions) (*v1alpha1.TaskLoop, error)
	Update(ctx context.Context, taskLoop *v1alpha1.TaskLoop, opts v1.UpdateOptions) (*v1alpha1.TaskLoop, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TaskLoop, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TaskLoopList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TaskLoop, err error)
	TaskLoopExpansion
}

// taskLoops implements TaskLoopInterface
type taskLoops struct {
	client rest.Interface
	ns     string
}

// newTaskLoops returns a TaskLoops
func newTaskLoops(c *CustomV1alpha1Client, namespace string) *taskLoops {
	return &taskLoops{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the taskLoop, and returns the corresponding taskLoop object, and an error if there is any.
func (c *taskLoops) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TaskLoop, err error) {
	result = &v1alpha1.TaskLoop{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("taskloops").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TaskLoops that match those selectors.
func (c *taskLoops) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TaskLoopList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TaskLoopList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("taskloops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested taskLoops.
func (c *taskLoops) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("taskloops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a taskLoop and creates it.  Returns the server's representation of the taskLoop, and an error, if there is any.
func (c *taskLoops) Create(ctx context.Context, taskLoop *v1alpha1.TaskLoop, opts v1.CreateOptions) (result *v1alpha1.TaskLoop, err error) {
	result = &v1alpha1.TaskLoop{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("taskloops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(taskLoop).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a taskLoop and updates it. Returns the server's representation of the taskLoop, and an error, if there is any.
func (c *taskLoops) Update(ctx context.Context, taskLoop *v1alpha1.TaskLoop, opts v1.UpdateOptions) (result *v1alpha1.TaskLoop, err error) {
	result = &v1alpha1.TaskLoop{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("taskloops").
		Name(taskLoop.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(taskLoop).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the taskLoop and deletes it. Returns an error if one occurs.
func (c *taskLoops) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("taskloops").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *taskLoops) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("taskloops").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched taskLoop.
func (c *taskLoops) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TaskLoop, err error) {
	result = &v1alpha1.TaskLoop{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("taskloops").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
