apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  generateName: celrun-get-type-
spec:
  ref:
    apiVersion: cel.dev/v1alpha1
    kind: CEL
  params:
    - name: expression
      value: "type(1)"
