apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-tekton-webhooks-extension
spec:
  resources:
    inputs:
      - name: source
        type: git
        targetPath: go/src/github.com/tektoncd/experimental
    outputs:
      - name: source
        type: git
  steps:
  - name: build-static
    image: gcr.io/tekton-releases/tests/test-runner@sha256:a4a64b2b70f85a618bbbcc6c0b713b313b2e410504dee24c9f90ec6fe3ebf63f
    workingDir: /workspace/go/src/github.com/tektoncd/experimental/webhooks-extension
    env:
    - name: GOPATH
      value: /workspace/go
    command: ["/bin/sh", "-ce"]
    args:
    - |
      set -e
      set -x
      
      echo "Installing yq"
      curl -O -L https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64
      mkdir -p yq-install
      mv yq_linux_amd64 yq-install/yq
      chmod +x yq-install/yq
      export PATH=$PATH:$(pwd)/yq-install

      apt-get update
      apt-get install -y curl
      curl -O https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz
      tar xf node-v10.15.3-linux-x64.tar.xz
      export PATH=$PATH:$(pwd)/node-v10.15.3-linux-x64/bin
      mkdir ~/.npm-global
      npm config set prefix '~/.npm-global'
      export PATH=$PATH:$HOME/.npm-global/bin
      npm ci
      
      npm run build_ko
      ls cmd/extension/kodata
      dep ensure -v
  - name: copy-files-to-output-resource
    image: busybox
    command: ["/bin/sh", "-ce"]
    args:
    - |
      # Further to https://github.com/tektoncd/pipeline/pull/1122 it is necessary to copy files into $(outputs.resources.source.path)
      echo "Input source path=$(resources.inputs.source.path)" 
      echo "Output source path=$(resources.outputs.source.path)"
      cp -r $(resources.inputs.source.path)/* $(resources.outputs.source.path)
