apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-tekton-webhooks-extension
spec:
  inputs:
    resources:
    - name: source
      type: git
      targetPath: go/src/github.com/tektoncd/experimental
  outputs:
    resources:
    - name: source
      type: git
  steps:
  - name: build-static
    image: gcr.io/tekton-releases/tests/test-runner@sha256:a4a64b2b70f85a618bbbcc6c0b713b313b2e410504dee24c9f90ec6fe3ebf63f
    workingDir: /workspace/go/src/github.com/tektoncd/experimental/webhooks-extension
    env:
    - name: GOPATH
      value: /workspace/go
    command: ["/bin/sh", "-ce"]
    args:
    - |
      set -e
      set -x

      apt-get update
      apt-get install -y curl
      curl -O https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz
      tar xf node-v10.15.3-linux-x64.tar.xz
      export PATH=$PATH:$(pwd)/node-v10.15.3-linux-x64/bin
      mkdir ~/.npm-global
      npm config set prefix '~/.npm-global'
      export PATH=$PATH:$HOME/.npm-global/bin
      npm ci
      
      npm run build_ko
      ls cmd/extension/kodata
      dep ensure -v
