apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-experimental-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/tektoncd/experimental 
  - name: revision
    value: INSERT_TAG_HERE
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-webhook-bucket
spec:
  type: storage
  params:
   - name: type
     value: gcs
   - name: location
     value: gs://tekton-releases/webhooks-extension # Append a /test-issue-nnn dir while developing. This needs to be created manually first.  
   - name: dir
     value: "y"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: webhooks-extension-extension-image
spec:
  type: image
  params:
   - name: url
     value: cmd/extension # Registry is provided via parameter, this is a hack see #569
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: webhooks-extension-interceptor-image
spec:
  type: image
  params:
   - name: url
     value: cmd/interceptor # Registry is provided via parameter, this is a hack see #569
