/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/metrics-operator/pkg/apis/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTaskRunMonitors implements TaskRunMonitorInterface
type FakeTaskRunMonitors struct {
	Fake *FakeMetricsV1alpha1
	ns   string
}

var taskrunmonitorsResource = schema.GroupVersionResource{Group: "metrics.tekton.dev", Version: "v1alpha1", Resource: "taskrunmonitors"}

var taskrunmonitorsKind = schema.GroupVersionKind{Group: "metrics.tekton.dev", Version: "v1alpha1", Kind: "TaskRunMonitor"}

// Get takes name of the taskRunMonitor, and returns the corresponding taskRunMonitor object, and an error if there is any.
func (c *FakeTaskRunMonitors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TaskRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(taskrunmonitorsResource, c.ns, name), &v1alpha1.TaskRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskRunMonitor), err
}

// List takes label and field selectors, and returns the list of TaskRunMonitors that match those selectors.
func (c *FakeTaskRunMonitors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TaskRunMonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(taskrunmonitorsResource, taskrunmonitorsKind, c.ns, opts), &v1alpha1.TaskRunMonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TaskRunMonitorList{ListMeta: obj.(*v1alpha1.TaskRunMonitorList).ListMeta}
	for _, item := range obj.(*v1alpha1.TaskRunMonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested taskRunMonitors.
func (c *FakeTaskRunMonitors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(taskrunmonitorsResource, c.ns, opts))

}

// Create takes the representation of a taskRunMonitor and creates it.  Returns the server's representation of the taskRunMonitor, and an error, if there is any.
func (c *FakeTaskRunMonitors) Create(ctx context.Context, taskRunMonitor *v1alpha1.TaskRunMonitor, opts v1.CreateOptions) (result *v1alpha1.TaskRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(taskrunmonitorsResource, c.ns, taskRunMonitor), &v1alpha1.TaskRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskRunMonitor), err
}

// Update takes the representation of a taskRunMonitor and updates it. Returns the server's representation of the taskRunMonitor, and an error, if there is any.
func (c *FakeTaskRunMonitors) Update(ctx context.Context, taskRunMonitor *v1alpha1.TaskRunMonitor, opts v1.UpdateOptions) (result *v1alpha1.TaskRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(taskrunmonitorsResource, c.ns, taskRunMonitor), &v1alpha1.TaskRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskRunMonitor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTaskRunMonitors) UpdateStatus(ctx context.Context, taskRunMonitor *v1alpha1.TaskRunMonitor, opts v1.UpdateOptions) (*v1alpha1.TaskRunMonitor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(taskrunmonitorsResource, "status", c.ns, taskRunMonitor), &v1alpha1.TaskRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskRunMonitor), err
}

// Delete takes name of the taskRunMonitor and deletes it. Returns an error if one occurs.
func (c *FakeTaskRunMonitors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(taskrunmonitorsResource, c.ns, name, opts), &v1alpha1.TaskRunMonitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTaskRunMonitors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(taskrunmonitorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TaskRunMonitorList{})
	return err
}

// Patch applies the patch and returns the patched taskRunMonitor.
func (c *FakeTaskRunMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TaskRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(taskrunmonitorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TaskRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskRunMonitor), err
}
