/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/metrics-operator/pkg/apis/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePipelineMonitors implements PipelineMonitorInterface
type FakePipelineMonitors struct {
	Fake *FakeMetricsV1alpha1
	ns   string
}

var pipelinemonitorsResource = schema.GroupVersionResource{Group: "metrics.tekton.dev", Version: "v1alpha1", Resource: "pipelinemonitors"}

var pipelinemonitorsKind = schema.GroupVersionKind{Group: "metrics.tekton.dev", Version: "v1alpha1", Kind: "PipelineMonitor"}

// Get takes name of the pipelineMonitor, and returns the corresponding pipelineMonitor object, and an error if there is any.
func (c *FakePipelineMonitors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PipelineMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pipelinemonitorsResource, c.ns, name), &v1alpha1.PipelineMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineMonitor), err
}

// List takes label and field selectors, and returns the list of PipelineMonitors that match those selectors.
func (c *FakePipelineMonitors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PipelineMonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pipelinemonitorsResource, pipelinemonitorsKind, c.ns, opts), &v1alpha1.PipelineMonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PipelineMonitorList{ListMeta: obj.(*v1alpha1.PipelineMonitorList).ListMeta}
	for _, item := range obj.(*v1alpha1.PipelineMonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pipelineMonitors.
func (c *FakePipelineMonitors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pipelinemonitorsResource, c.ns, opts))

}

// Create takes the representation of a pipelineMonitor and creates it.  Returns the server's representation of the pipelineMonitor, and an error, if there is any.
func (c *FakePipelineMonitors) Create(ctx context.Context, pipelineMonitor *v1alpha1.PipelineMonitor, opts v1.CreateOptions) (result *v1alpha1.PipelineMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pipelinemonitorsResource, c.ns, pipelineMonitor), &v1alpha1.PipelineMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineMonitor), err
}

// Update takes the representation of a pipelineMonitor and updates it. Returns the server's representation of the pipelineMonitor, and an error, if there is any.
func (c *FakePipelineMonitors) Update(ctx context.Context, pipelineMonitor *v1alpha1.PipelineMonitor, opts v1.UpdateOptions) (result *v1alpha1.PipelineMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pipelinemonitorsResource, c.ns, pipelineMonitor), &v1alpha1.PipelineMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineMonitor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePipelineMonitors) UpdateStatus(ctx context.Context, pipelineMonitor *v1alpha1.PipelineMonitor, opts v1.UpdateOptions) (*v1alpha1.PipelineMonitor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pipelinemonitorsResource, "status", c.ns, pipelineMonitor), &v1alpha1.PipelineMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineMonitor), err
}

// Delete takes name of the pipelineMonitor and deletes it. Returns an error if one occurs.
func (c *FakePipelineMonitors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(pipelinemonitorsResource, c.ns, name, opts), &v1alpha1.PipelineMonitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePipelineMonitors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pipelinemonitorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PipelineMonitorList{})
	return err
}

// Patch applies the patch and returns the patched pipelineMonitor.
func (c *FakePipelineMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelineMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pipelinemonitorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PipelineMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineMonitor), err
}
