/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/metrics-operator/pkg/apis/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePipelineRunMonitors implements PipelineRunMonitorInterface
type FakePipelineRunMonitors struct {
	Fake *FakeMetricsV1alpha1
	ns   string
}

var pipelinerunmonitorsResource = schema.GroupVersionResource{Group: "metrics.tekton.dev", Version: "v1alpha1", Resource: "pipelinerunmonitors"}

var pipelinerunmonitorsKind = schema.GroupVersionKind{Group: "metrics.tekton.dev", Version: "v1alpha1", Kind: "PipelineRunMonitor"}

// Get takes name of the pipelineRunMonitor, and returns the corresponding pipelineRunMonitor object, and an error if there is any.
func (c *FakePipelineRunMonitors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PipelineRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pipelinerunmonitorsResource, c.ns, name), &v1alpha1.PipelineRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineRunMonitor), err
}

// List takes label and field selectors, and returns the list of PipelineRunMonitors that match those selectors.
func (c *FakePipelineRunMonitors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PipelineRunMonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pipelinerunmonitorsResource, pipelinerunmonitorsKind, c.ns, opts), &v1alpha1.PipelineRunMonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PipelineRunMonitorList{ListMeta: obj.(*v1alpha1.PipelineRunMonitorList).ListMeta}
	for _, item := range obj.(*v1alpha1.PipelineRunMonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pipelineRunMonitors.
func (c *FakePipelineRunMonitors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pipelinerunmonitorsResource, c.ns, opts))

}

// Create takes the representation of a pipelineRunMonitor and creates it.  Returns the server's representation of the pipelineRunMonitor, and an error, if there is any.
func (c *FakePipelineRunMonitors) Create(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.CreateOptions) (result *v1alpha1.PipelineRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pipelinerunmonitorsResource, c.ns, pipelineRunMonitor), &v1alpha1.PipelineRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineRunMonitor), err
}

// Update takes the representation of a pipelineRunMonitor and updates it. Returns the server's representation of the pipelineRunMonitor, and an error, if there is any.
func (c *FakePipelineRunMonitors) Update(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.UpdateOptions) (result *v1alpha1.PipelineRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pipelinerunmonitorsResource, c.ns, pipelineRunMonitor), &v1alpha1.PipelineRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineRunMonitor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePipelineRunMonitors) UpdateStatus(ctx context.Context, pipelineRunMonitor *v1alpha1.PipelineRunMonitor, opts v1.UpdateOptions) (*v1alpha1.PipelineRunMonitor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pipelinerunmonitorsResource, "status", c.ns, pipelineRunMonitor), &v1alpha1.PipelineRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineRunMonitor), err
}

// Delete takes name of the pipelineRunMonitor and deletes it. Returns an error if one occurs.
func (c *FakePipelineRunMonitors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(pipelinerunmonitorsResource, c.ns, name, opts), &v1alpha1.PipelineRunMonitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePipelineRunMonitors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pipelinerunmonitorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PipelineRunMonitorList{})
	return err
}

// Patch applies the patch and returns the patched pipelineRunMonitor.
func (c *FakePipelineRunMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelineRunMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pipelinerunmonitorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PipelineRunMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelineRunMonitor), err
}
