/*
Copyright 2021 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/workflows/pkg/apis/workflows/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGitRepositories implements GitRepositoryInterface
type FakeGitRepositories struct {
	Fake *FakeWorkflowsV1alpha1
	ns   string
}

var gitrepositoriesResource = schema.GroupVersionResource{Group: "workflows.tekton.dev", Version: "v1alpha1", Resource: "gitrepositories"}

var gitrepositoriesKind = schema.GroupVersionKind{Group: "workflows.tekton.dev", Version: "v1alpha1", Kind: "GitRepository"}

// Get takes name of the gitRepository, and returns the corresponding gitRepository object, and an error if there is any.
func (c *FakeGitRepositories) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GitRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gitrepositoriesResource, c.ns, name), &v1alpha1.GitRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitRepository), err
}

// List takes label and field selectors, and returns the list of GitRepositories that match those selectors.
func (c *FakeGitRepositories) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GitRepositoryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gitrepositoriesResource, gitrepositoriesKind, c.ns, opts), &v1alpha1.GitRepositoryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GitRepositoryList{ListMeta: obj.(*v1alpha1.GitRepositoryList).ListMeta}
	for _, item := range obj.(*v1alpha1.GitRepositoryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gitRepositories.
func (c *FakeGitRepositories) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gitrepositoriesResource, c.ns, opts))

}

// Create takes the representation of a gitRepository and creates it.  Returns the server's representation of the gitRepository, and an error, if there is any.
func (c *FakeGitRepositories) Create(ctx context.Context, gitRepository *v1alpha1.GitRepository, opts v1.CreateOptions) (result *v1alpha1.GitRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gitrepositoriesResource, c.ns, gitRepository), &v1alpha1.GitRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitRepository), err
}

// Update takes the representation of a gitRepository and updates it. Returns the server's representation of the gitRepository, and an error, if there is any.
func (c *FakeGitRepositories) Update(ctx context.Context, gitRepository *v1alpha1.GitRepository, opts v1.UpdateOptions) (result *v1alpha1.GitRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gitrepositoriesResource, c.ns, gitRepository), &v1alpha1.GitRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitRepository), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGitRepositories) UpdateStatus(ctx context.Context, gitRepository *v1alpha1.GitRepository, opts v1.UpdateOptions) (*v1alpha1.GitRepository, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gitrepositoriesResource, "status", c.ns, gitRepository), &v1alpha1.GitRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitRepository), err
}

// Delete takes name of the gitRepository and deletes it. Returns an error if one occurs.
func (c *FakeGitRepositories) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gitrepositoriesResource, c.ns, name, opts), &v1alpha1.GitRepository{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGitRepositories) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gitrepositoriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GitRepositoryList{})
	return err
}

// Patch applies the patch and returns the patched gitRepository.
func (c *FakeGitRepositories) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GitRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gitrepositoriesResource, c.ns, name, pt, data, subresources...), &v1alpha1.GitRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitRepository), err
}
