apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: monitor-task-template
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-webhooks-extension
spec:
  params:
  - name: pullrequesturl
    description: The pull request url
  - name: statusesurl
    description: The statuses url
  - name: gitsecretname
    description: The git secret name
    default: github-secrets
  - name: gitsecretkeyname
    description: The git secret key name
    default: token
  - name: commentsuccess
    description: The text of the success comment
    default: "Success"
  - name: commentfailure
    description: The text of the failure comment
    default: "Failed"
  - name: commenttimeout
    description: The text of the timeout comment
    default: "Unknown"
  - name: commentmissing
    description: The text of the missing comment
    default: "Missing"
  - name: dashboardurl
    description: The URL to the pipelineruns page of the dashboard
    default: "http://localhost:9097/"
  - name: provider
    description: The git provider, "github" or "gitlab"
    default: "github"
  - name: apiurl
    description: The git api URL for the repository
    default: ""
  - name: insecure-skip-tls-verify
    description: Whether or not to skip SSL validation of certificates ("true" or "false")
    default: "false"
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: pull-request-$(uid)
    spec:
      type: pullRequest
      params:
        - name: url
          value: $(params.pullrequesturl)
        - name: insecure-skip-tls-verify
          value: $(params.insecure-skip-tls-verify)
      secrets:
        - fieldName: authToken
          secretName: $(params.gitsecretname)
          secretKey: $(params.gitsecretkeyname)
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: monitor-taskrun-
    spec:
      serviceAccountName: tekton-webhooks-extension
      taskRef:
        name: monitor-task
      params:
        - name: commentsuccess
          value: $(params.commentsuccess)
        - name: commentfailure
          value: $(params.commentfailure)
        - name: commenttimeout
          value: $(params.commenttimeout)
        - name: dashboard-url
          value: $(params.dashboardurl)
        - name: secret
          value: $(params.gitsecretname)
        - name: statusesurl
          value: $(params.statusesurl)
        - name: provider
          value: $(params.provider)
        - name: apiurl
          value: $(params.apiurl)
        - name: insecure-skip-tls-verify
          value: $(params.insecure-skip-tls-verify)
      resources:
        inputs:
          - name: pull-request
            resourceRef:
              name: pull-request-$(uid)
        outputs:
          - name: pull-request
            resourceRef:
              name: pull-request-$(uid)