apiVersion: tekton.dev/v1alpha1
kind: Workflow
metadata:
  name: example-workflow
spec:
  pipeline:
    spec:
      tasks:
      - name: echo-hello
        taskSpec:
          steps:
          - image: busybox
            script: echo "hello"
  params:
    - name: default-repo
      default: my-repo
