apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    pod-group.scheduling.sigs.k8s.io/name: test
    pod-group.scheduling.sigs.k8s.io/total: "2"
spec:
  schedulerName: scheduler-framework-sample
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: "4000m"
        limits:
          cpu: "4000m"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: static-web-1
  labels:
    pod-group.scheduling.sigs.k8s.io/name: test
    pod-group.scheduling.sigs.k8s.io/total: "2"
spec:
  schedulerName: scheduler-framework-sample
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: "4000m"
        limits:
          cpu: "4000m"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
