apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: concurrencycontrols.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-concurrency
    pipeline.tekton.dev/release: "devel"
    version: "devel"
spec:
  group: tekton.dev
  scope: Namespaced
  names:
    kind: ConcurrencyControl
    plural: concurrencycontrols
    singular: concurrencycontrol
    shortNames:
    - cc
    categories:
    - tekton
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
