apiVersion: v1
kind: ConfigMap
metadata:
  name: concurrency-config
  namespace: tekton-concurrency
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-concurrency
data:
  # An optional comma-separated list of namespaces that can use concurrency controls.
  # Defaults to empty, meaning all namespaces are allowed.
  allowed-namespaces: ""
