# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## TODO

# apiVersion: v1
# kind: Secret
# metadata:
#   name: webhook-certs
#   namespace: tekton-pipelines
#   labels:
#     pipeline.tekton.dev/release: devel
# # The data is populated at install time.
# ---
{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "triggers.fullname" . }}-validation
  labels:
    app.kubernetes.io/name: {{ template "triggers.name" . }}
    app.kubernetes.io/component: admission
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "triggers.chart" . }}
    triggers.tekton.dev/release: {{ .Values.version | quote }}
    version: {{ .Values.version | quote }}
webhooks:
  - name: validation.webhook.triggers.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "triggers.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "triggers.fullname" . }}-webhook
  labels:
    app.kubernetes.io/name: {{ template "triggers.name" . }}
    app.kubernetes.io/component: admission
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "triggers.chart" . }}
    triggers.tekton.dev/release: {{ .Values.version | quote }}
    version: {{ .Values.version | quote }}
webhooks:
  - name: webhook.triggers.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "triggers.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "triggers.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ template "triggers.name" . }}
    app.kubernetes.io/component: admission
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "triggers.chart" . }}
    triggers.tekton.dev/release: {{ .Values.version | quote }}
    version: {{ .Values.version | quote }}
webhooks:
  - name: config.webhook.triggers.tekton.dev
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ template "triggers.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: triggers.tekton.dev/release
          operator: Exists
{{- end }}
