/*
Copyright 2021 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/celeval/pkg/apis/celeval/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCELEvals implements CELEvalInterface
type FakeCELEvals struct {
	Fake *FakeCustomV1alpha1
	ns   string
}

var celevalsResource = schema.GroupVersionResource{Group: "custom.tekton.dev", Version: "v1alpha1", Resource: "celevals"}

var celevalsKind = schema.GroupVersionKind{Group: "custom.tekton.dev", Version: "v1alpha1", Kind: "CELEval"}

// Get takes name of the cELEval, and returns the corresponding cELEval object, and an error if there is any.
func (c *FakeCELEvals) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CELEval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(celevalsResource, c.ns, name), &v1alpha1.CELEval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CELEval), err
}

// List takes label and field selectors, and returns the list of CELEvals that match those selectors.
func (c *FakeCELEvals) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CELEvalList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(celevalsResource, celevalsKind, c.ns, opts), &v1alpha1.CELEvalList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CELEvalList{ListMeta: obj.(*v1alpha1.CELEvalList).ListMeta}
	for _, item := range obj.(*v1alpha1.CELEvalList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cELEvals.
func (c *FakeCELEvals) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(celevalsResource, c.ns, opts))

}

// Create takes the representation of a cELEval and creates it.  Returns the server's representation of the cELEval, and an error, if there is any.
func (c *FakeCELEvals) Create(ctx context.Context, cELEval *v1alpha1.CELEval, opts v1.CreateOptions) (result *v1alpha1.CELEval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(celevalsResource, c.ns, cELEval), &v1alpha1.CELEval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CELEval), err
}

// Update takes the representation of a cELEval and updates it. Returns the server's representation of the cELEval, and an error, if there is any.
func (c *FakeCELEvals) Update(ctx context.Context, cELEval *v1alpha1.CELEval, opts v1.UpdateOptions) (result *v1alpha1.CELEval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(celevalsResource, c.ns, cELEval), &v1alpha1.CELEval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CELEval), err
}

// Delete takes name of the cELEval and deletes it. Returns an error if one occurs.
func (c *FakeCELEvals) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(celevalsResource, c.ns, name), &v1alpha1.CELEval{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCELEvals) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(celevalsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CELEvalList{})
	return err
}

// Patch applies the patch and returns the patched cELEval.
func (c *FakeCELEvals) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CELEval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(celevalsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CELEval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CELEval), err
}
