/*
Copyright 2021 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/remote-resolution/pkg/apis/resolution/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceRequests implements ResourceRequestInterface
type FakeResourceRequests struct {
	Fake *FakeResolutionV1alpha1
	ns   string
}

var resourcerequestsResource = schema.GroupVersionResource{Group: "resolution.tekton.dev", Version: "v1alpha1", Resource: "resourcerequests"}

var resourcerequestsKind = schema.GroupVersionKind{Group: "resolution.tekton.dev", Version: "v1alpha1", Kind: "ResourceRequest"}

// Get takes name of the resourceRequest, and returns the corresponding resourceRequest object, and an error if there is any.
func (c *FakeResourceRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ResourceRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourcerequestsResource, c.ns, name), &v1alpha1.ResourceRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceRequest), err
}

// List takes label and field selectors, and returns the list of ResourceRequests that match those selectors.
func (c *FakeResourceRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ResourceRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourcerequestsResource, resourcerequestsKind, c.ns, opts), &v1alpha1.ResourceRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourceRequestList{ListMeta: obj.(*v1alpha1.ResourceRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourceRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceRequests.
func (c *FakeResourceRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourcerequestsResource, c.ns, opts))

}

// Create takes the representation of a resourceRequest and creates it.  Returns the server's representation of the resourceRequest, and an error, if there is any.
func (c *FakeResourceRequests) Create(ctx context.Context, resourceRequest *v1alpha1.ResourceRequest, opts v1.CreateOptions) (result *v1alpha1.ResourceRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourcerequestsResource, c.ns, resourceRequest), &v1alpha1.ResourceRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceRequest), err
}

// Update takes the representation of a resourceRequest and updates it. Returns the server's representation of the resourceRequest, and an error, if there is any.
func (c *FakeResourceRequests) Update(ctx context.Context, resourceRequest *v1alpha1.ResourceRequest, opts v1.UpdateOptions) (result *v1alpha1.ResourceRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourcerequestsResource, c.ns, resourceRequest), &v1alpha1.ResourceRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeResourceRequests) UpdateStatus(ctx context.Context, resourceRequest *v1alpha1.ResourceRequest, opts v1.UpdateOptions) (*v1alpha1.ResourceRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(resourcerequestsResource, "status", c.ns, resourceRequest), &v1alpha1.ResourceRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceRequest), err
}

// Delete takes name of the resourceRequest and deletes it. Returns an error if one occurs.
func (c *FakeResourceRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourcerequestsResource, c.ns, name), &v1alpha1.ResourceRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourcerequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceRequestList{})
	return err
}

// Patch applies the patch and returns the patched resourceRequest.
func (c *FakeResourceRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcerequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ResourceRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceRequest), err
}
