# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pipeline-run
  annotations:
    "tekton.dev/git-status": "true"
    "tekton.dev/status-context": "commit-status-tracker-demo"
    "tekton.dev/status-description": "This is coming from pipeline_run_with_git.yaml"
spec:
  pipelineRef:
    name: demo-pipeline
  serviceAccountName: default
  resources:
  - name: source
    resourceSpec:
      type: git
      params:
        - name: url
          value: <REPLACE THIS WITH A GIT REPO YOU OWN>
        - name: revision
          value: <REPLACE THIS WITH THE FULL GIT SHA OF AN OPEN PULL REQUEST - THIS WILL MAKE IT EASY TO SEE IN THE CHECKS>
